improved install and run

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,4 +1,31 @@
 #!/bin/bash
+# Install the morpho-syntactic parser.
+# Alpino:
+# if variable ALPINO_HOME does not exist, find or try to install Alpino within the directory of this module.
+# Otherwise, find or try to install Alpino in where ALPINO_HOME points to.
+# Exit in failure when in the end Alpino does not seem to be installed.
+# If that variable does not exist, install the latest Alpino in the directory of the module itself.
 thisdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 cd $thisdir
+#
+# set up Alpino
+#
+ALPINO_DEF=$thisdir/Alpino
+ALPINO_HOME=${1:-$ALPINO_HOME}
+ALPINO_HOME=${ALPINO_HOME:-$ALPINO_DEF}
+if
+  [ ! -x "${ALPINO_HOME}/bin/alpino" ]
+then
+  export ALPINO_SOCK=$(dirname $ALPINO_HOME)
+  ./install_alpino $ALPINO_SOCK
+  if
+     [ $? -gt 0 ]
+  then
+     echo "Cannot install Alpino in $ALPINO_HOME"
+     exit 4
+  fi
+fi  
+#
+# Set up this module
+#
 python3 ./setup.py
diff --git a/run b/run
--- a/run
+++ b/run
@@ -1,8 +1,49 @@
 #!/bin/bash
+# Opional option "-a <alpino_option>"
+# Option "-t maxtime" 
+# Set ALPINO_HOME in hierarchy: 1) alpino_option; 2) ALPINO_HOME; 3) default (ALPINO_DEFAULT)
 thisdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+#
+# Get "-a" or "-t" option if present.
+#
+opts=""
+while getopts a:t: opt; do
+   case $opt in
+     a) ALPINO_CLOPT=$OPTARG
+        ;;
+     t) MAX_TIME=$OPTARG
+        ;;
+     *) echo "Unknown option." 
+        exit 1
+        ;;
+    esac
+done
+#
+# Set ALPINO_HOME
+#
+ALPINO_DEFAULT=$thisdir/Alpino
+ALPINO_HOME=${ALPINO_CLOPT:-$ALPINO_HOME}
+ALPINO_HOME=${ALPINO_HOME:-$ALPINO_DEFAULT}
 cd $thisdir
-python3 -m alpinonaf
-
+#
+# Check for Alpino
+#
+if
+  [ ! -x "${ALPINO_HOME}/bin/alpino" ]
+then
+  echo "Cannot find Alpino" >&2
+  exit 4
+fi
+#
+# Run
+#
+if 
+  [ -z "$MAX_TIME" ]
+then
+  python3 -m alpinonaf
+else
+  python3 -m alpinonaf -t $MAX_TIME
+fi
 #For instance to set the maximum number of minutes per sentence to 5 minutes:
 ###python $this_dir/core/morph_syn_parser.py -t 5
 
